### ISSUE TITLE
07-c-language : Build failed

### ISSUE THREAD

**Issue by alexwang3322** [ysoftdevs/gradle-training#1]
When I run command "gradle mainExecutable" at folder "07-c-language" , a problem occurs:
- What went wrong:
  A problem occurred evaluating root project '07-c-language'.
  
  > Could not find method main() for arguments [build_boktgcsy0nabp9jw2aso8xe1k$_run_closure1_closure3@70aaa836] on root project '07-c-language'.
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.GradleScriptException: A problem occurred evaluating root project '07-c-language'.
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
  at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)

I can't understand what 's the problem,plz give a sign or solve, thanks much :)

**Comment by georgik** [comment]
Hi Alex.

New version of Gradle has different syntax form C/C++ plugins.
Here is sample: http://stackoverflow.com/questions/29134071/building-c-program-with-gradle

Pull latest version, I made correction there.

**Comment by georgik** [comment]
Fixed also example 08.
Thank you for pointing out the issue.
